/*----------------------------------------------------------------------------
 * Filename: OEM_SMBus.H  For Chipset: ITE.IT85XX
 *
 * Author  : Dino
 * 
 * Copyright (c) 2009 - , ITE Tech. Inc. All Rights Reserved. 
 *
 * You may not present,reproduce,distribute,publish,display,modify,adapt,
 * perform,transmit,broadcast,recite,release,license or otherwise exploit
 * any part of this publication in any form,by any means,without the prior
 * written permission of ITE Tech. Inc.	
 *---------------------------------------------------------------------------*/

#ifndef OEM_SMBUS_H
#define OEM_SMBUS_H

extern void Hook_GetSMBusReadBlockByteCount(BYTE rblk_bc);

#endif