/*-----------------------------------------------------------------------------
 * TITLE: OEM_BANK3_Func.H
 *
 * Author : Dino
 *
 * Note : These functions are reference only.
 *        Please follow your project software specification to do some modification.
 *---------------------------------------------------------------------------*/
#ifndef OEM_BANK3_Func_H
#define OEM_BANK3_Func_H

extern void Bank3_Test(void);



#endif