/*-----------------------------------------------------------------------------
 * TITLE: OEM_BANK1_Func.H
 *
 * Author : Dino
 *
 * Note : These functions are reference only.
 *        Please follow your project software specification to do some modification.
 *---------------------------------------------------------------------------*/
#ifndef OEM_BANK1_Func_H
#define OEM_BANK1_Func_H


extern void Bank1_Test(void);


#endif