/*-----------------------------------------------------------------------------
 * TITLE: CORE_HSPI.H
 *
 * Copyright (c) 2009- , ITE Corporation. All Rights Reserved.
 *
 * You may not reproduce, distribute, publish, display, perform, modify, adapt,
 * transmit, broadcast, present, recite, release, license or otherwise exploit
 * any part of this publication in any form, by any means, without the prior
 * written permission of Insyde Software Corporation.
 *---------------------------------------------------------------------------*/
 
#ifndef CORE_HSPI_H
#define CORE_HSPI_H


extern void ChangePLLFrequency(BYTE newseting);

#endif
