/*-----------------------------------------------------------------------------
 * TITLE: OEM_CIR.H
 *
 * Author : Dino
 *
 * Note : These functions are reference only.
 *        Please follow your project software specification to do some modification.
 *---------------------------------------------------------------------------*/

#ifndef	OEM_CIR_H
#define OEM_CIR_H

extern void service_cir(void);

#endif