/*-----------------------------------------------------------------------------
 * TITLE: OEM_BANK2_Func.H
 *
 * Author : Dino
 *
 * Note : These functions are reference only.
 *        Please follow your project software specification to do some modification.
 *---------------------------------------------------------------------------*/
#ifndef OEM_BANK2_Func_H
#define OEM_BANK2_Func_H


extern void Bank2_Test(void);


#endif